
import { SelectProps } from 'antd';
export const seasoningOptions: SelectProps['options'] = [
  { label: 'Flour', value: 'flour', desc: 'Flour' },
  { label: 'Salt', value: 'salt', desc: 'Salt' },
  { label: 'Garlic, herbs', value: 'garlic_herbs', desc: 'Garlic, herbs' },
  { label: 'Parmesan cheese', value: 'parmesan_cheese', desc: 'Parmesan cheese' },
  { label: 'Lettuce, Parmesan cheese', value: 'lettuce_parmesan_cheese', desc: 'Lettuce, Parmesan cheese' },
  { label: 'None', value: 'none', desc: 'None' },
  { label: 'Tomato sauce', value: 'tomato_sauce', desc: 'Tomato sauce' },
  { label: 'Tomato sauce, basil', value: 'tomato_sauce_basil', desc: 'Tomato sauce, basil' },
  { label: 'Salt, Pepper', value: 'salt_pepper', desc: 'Salt, Pepper' },
  { label: 'Mozzarella cheese, basil', value: 'mozzarella_cheese_basil', desc: 'Mozzarella cheese, basil' },
  { label: 'Caesar dressing', value: 'caesar_dressing', desc: 'Caesar dressing' },
  { label: 'Granola', value: 'granola', desc: 'Granola' },
  { label: 'Cream, Parmesan cheese', value: 'cream_parmesan_cheese', desc: 'Cream, Parmesan cheese' },
  { label: 'Mushroom, onion', value: 'mushroom_onion', desc: 'Mushroom, onion' },
  { label: 'Feta cheese, mint', value: 'feta_cheese_mint', desc: 'Feta cheese, mint' },
  { label: 'Marinara sauce', value: 'marinara_sauce', desc: 'Marinara sauce' },
  { label: 'Cardamom', value: 'cardamom', desc: 'Cardamom' },
  { label: 'Feta cheese, olives', value: 'feta_cheese_olives', desc: 'Feta cheese, olives' },
  { label: 'Vegetable broth', value: 'vegetable_broth', desc: 'Vegetable broth' },
  { label: 'Fresh tomatoes, mozzarella', value: 'fresh_tomatoes_mozzarella', desc: 'Fresh tomatoes, mozzarella' },
  { label: 'Tzatziki sauce, tomatoes, onions', value: 'tzatziki_sauce_tomatoes_onions', desc: 'Tzatziki sauce, tomatoes, onions' },
  { label: 'Spinach, feta cheese', value: 'spinach_feta_cheese', desc: 'Spinach, feta cheese' },
  { label: 'Arborio rice, Parmesan cheese', value: 'arborio_rice_parmesan_cheese', desc: 'Arborio rice, Parmesan cheese' },
  { label: 'Granola, mixed berries', value: 'granola_mixed_berries', desc: 'Granola, mixed berries' },
  { label: 'Marinara sauce, cheese', value: 'marinara_sauce_cheese', desc: 'Marinara sauce, cheese' },
  { label: 'Vanilla pudding mix, cookies', value: 'vanilla_pudding_mix_cookies', desc: 'Vanilla pudding mix, cookies' },
  { label: 'Mozzarella cheese, tomatoes, basil', value: 'mozzarella_cheese_tomatoes_basil', desc: 'Mozzarella cheese, tomatoes, basil' },
  { label: 'Romaine lettuce, Parmesan cheese', value: 'romaine_lettuce_parmesan_cheese', desc: 'Romaine lettuce, Parmesan cheese' },
  { label: 'Feta cheese, phyllo dough', value: 'feta_cheese_phyllo_dough', desc: 'Feta cheese, phyllo dough' },
  { label: 'Parmesan cheese, garlic', value: 'parmesan_cheese_garlic', desc: 'Parmesan cheese, garlic' },
  { label: 'Vanilla extract', value: 'vanilla_extract', desc: 'Vanilla extract' },
  { label: 'Cheese, breadcrumbs', value: 'cheese_breadcrumbs', desc: 'Cheese, breadcrumbs' },
  { label: 'Tandoori spices', value: 'tandoori_spices', desc: 'Tandoori spices' },
  { label: 'Mushrooms, onions', value: 'mushrooms_onions', desc: 'Mushrooms, onions' },
  { label: 'Milk', value: 'milk', desc: 'Milk' },
  { label: 'Goat cheese, herbs', value: 'goat_cheese_herbs', desc: 'Goat cheese, herbs' },
  { label: 'Nutmeg, cream', value: 'nutmeg_cream', desc: 'Nutmeg, cream' },
  { label: 'Lemon, capers', value: 'lemon_capers', desc: 'Lemon, capers' },
  { label: 'Tomato sauce, cream', value: 'tomato_sauce_cream', desc: 'Tomato sauce, cream' },
  { label: 'Paneer, spices', value: 'paneer_spices', desc: 'Paneer, spices' },
  { label: 'Yogurt, Kashmiri red chili', value: 'yogurt_kashmiri_red_chili', desc: 'Yogurt, Kashmiri red chili' },
  { label: 'Tikka masala, spices', value: 'tikka_masala_spices', desc: 'Tikka masala, spices' },
  { label: 'Cream, spices', value: 'cream_spices', desc: 'Cream, spices' },
  { label: 'Creamy tomato sauce', value: 'creamy_tomato_sauce', desc: 'Creamy tomato sauce' },
  { label: 'Cardamom syrup', value: 'cardamom_syrup', desc: 'Cardamom syrup' },
  { label: 'Creamy sauce, spices', value: 'creamy_sauce_spices', desc: 'Creamy sauce, spices' },
  { label: 'Spices', value: 'spices', desc: 'Spices' },
  { label: 'Tamarind chutney, spices', value: 'tamarind_chutney_spices', desc: 'Tamarind chutney, spices' },
  { label: 'Peas, spices', value: 'peas_spices', desc: 'Peas, spices' },
  { label: 'Rose water, syrup', value: 'rose_water_syrup', desc: 'Rose water, syrup' },
  { label: 'Cardamom, nuts', value: 'cardamom_nuts', desc: 'Cardamom, nuts' },
  { label: 'Cheese, eggs', value: 'cheese_eggs', desc: 'Cheese, eggs' },
  { label: 'Tikka masala sauce', value: 'tikka_masala_sauce', desc: 'Tikka masala sauce' },
  { label: 'Cinnamon, nutmeg', value: 'cinnamon_nutmeg', desc: 'Cinnamon, nutmeg' },
  { label: 'Herbs, nuts', value: 'herbs_nuts', desc: 'Herbs, nuts' },
  { label: 'Beef broth, cheese, bread', value: 'beef_broth_cheese_bread', desc: 'Beef broth, cheese, bread' },
  { label: 'Tzatziki sauce, vegetables', value: 'tzatziki_sauce_vegetables', desc: 'Tzatziki sauce, vegetables' },
  { label: 'Salt, pepper', value: 'salt_pepper', desc: 'Salt, pepper' },
  { label: 'Celery, onion', value: 'celery_onion', desc: 'Celery, onion' },
  { label: 'Vegetables', value: 'vegetables', desc: 'Vegetables' },
  { label: 'Celery, mustard', value: 'celery_mustard', desc: 'Celery, mustard' },
  { label: 'Soy sauce', value: 'soy_sauce', desc: 'Soy sauce' },
  { label: 'Lemon, herbs', value: 'lemon_herbs', desc: 'Lemon, herbs' },
  { label: 'Teriyaki sauce', value: 'teriyaki_sauce', desc: 'Teriyaki sauce' },
  { label: 'Lemon, dill', value: 'lemon_dill', desc: 'Lemon, dill' },
  { label: 'Tamarind, spices', value: 'tamarind_spices', desc: 'Tamarind, spices' },
  { label: 'Ginger, garlic', value: 'ginger_garlic', desc: 'Ginger, garlic' },
  { label: 'Raw fish, vegetables', value: 'raw_fish_vegetables', desc: 'Raw fish, vegetables' },
  { label: 'Garlic, ginger', value: 'garlic_ginger', desc: 'Garlic, ginger' },
  { label: 'Pectin', value: 'pectin', desc: 'Pectin' },
  { label: 'Salt, Sugar', value: 'salt_sugar', desc: 'Salt, Sugar' },
  { label: 'Lemon juice', value: 'lemon_juice', desc: 'Lemon juice' },
  { label: 'Vegetable oil', value: 'vegetable_oil', desc: 'Vegetable oil' },
  { label: 'BBQ sauce', value: 'bbq_sauce', desc: 'BBQ sauce' },
  { label: 'Lemon juice, herbs', value: 'lemon_juice_herbs', desc: 'Lemon juice, herbs' },
  { label: 'Taco seasoning', value: 'taco_seasoning', desc: 'Taco seasoning' },
  { label: 'Curry powder', value: 'curry_powder', desc: 'Curry powder' },
  { label: 'Tomatoes', value: 'tomatoes', desc: 'Tomatoes' },
  { label: 'Basil, garlic', value: 'basil_garlic', desc: 'Basil, garlic' },
  { label: 'Seasonings', value: 'seasonings', desc: 'Seasonings' },
  { label: 'Balsamic vinegar', value: 'balsamic_vinegar', desc: 'Balsamic vinegar' },
  { label: 'Enchilada sauce', value: 'enchilada_sauce', desc: 'Enchilada sauce' },
  { label: 'Tomato broth', value: 'tomato_broth', desc: 'Tomato broth' },
  { label: 'Onion, cilantro', value: 'onion_cilantro', desc: 'Onion, cilantro' },
  { label: 'Lemon juice, garlic', value: 'lemon_juice_garlic', desc: 'Lemon juice, garlic' },
  { label: 'Spinach, garlic', value: 'spinach_garlic', desc: 'Spinach, garlic' },
  { label: 'Curry paste', value: 'curry_paste', desc: 'Curry paste' },
  { label: 'Cinnamon', value: 'cinnamon', desc: 'Cinnamon' },
  { label: 'Tomatoes, zucchini', value: 'tomatoes_zucchini', desc: 'Tomatoes, zucchini' },
  { label: 'Lemon juice, dill', value: 'lemon_juice_dill', desc: 'Lemon juice, dill' },
  { label: 'Mozzarella cheese', value: 'mozzarella_cheese', desc: 'Mozzarella cheese' },
  { label: 'Fajita seasoning', value: 'fajita_seasoning', desc: 'Fajita seasoning' },
  { label: 'Red onion, lime', value: 'red_onion_lime', desc: 'Red onion, lime' },
  { label: 'Almond milk', value: 'almond_milk', desc: 'Almond milk' },
  { label: 'Ground meat, rice', value: 'ground_meat_rice', desc: 'Ground meat, rice' },
  { label: 'Salt, paprika', value: 'salt_paprika', desc: 'Salt, paprika' },
  { label: 'Chili powder', value: 'chili_powder', desc: 'Chili powder' },
  { label: 'Shawarma spices', value: 'shawarma_spices', desc: 'Shawarma spices' },
  { label: 'Pineapple, bell peppers', value: 'pineapple_bell_peppers', desc: 'Pineapple, bell peppers' },
  { label: 'Garlic, basil', value: 'garlic_basil', desc: 'Garlic, basil' },
  { label: 'Vegetables, spices', value: 'vegetables_spices', desc: 'Vegetables, spices' },
  { label: 'Herbs, garlic', value: 'herbs_garlic', desc: 'Herbs, garlic' },
  { label: 'Lemon juice, vegetables', value: 'lemon_juice_vegetables', desc: 'Lemon juice, vegetables' },
  { label: 'Buffalo sauce', value: 'buffalo_sauce', desc: 'Buffalo sauce' },
  { label: 'Orange sauce', value: 'orange_sauce', desc: 'Orange sauce' },
  { label: 'Mustard, herbs', value: 'mustard_herbs', desc: 'Mustard, herbs' },
  { label: 'Cilantro, lime', value: 'cilantro_lime', desc: 'Cilantro, lime' },
  { label: 'Ratatouille vegetables', value: 'ratatouille_vegetables', desc: 'Ratatouille vegetables' },
  { label: 'Tomatoes, vegetables', value: 'tomatoes_vegetables', desc: 'Tomatoes, vegetables' },
  { label: 'Ground meat, potatoes', value: 'ground_meat_potatoes', desc: 'Ground meat, potatoes' },
  { label: 'Balsamic glaze', value: 'balsamic_glaze', desc: 'Balsamic glaze' },
  { label: 'Noodles, vegetables', value: 'noodles_vegetables', desc: 'Noodles, vegetables' },
  { label: 'Lime juice, cilantro', value: 'lime_juice_cilantro', desc: 'Lime juice, cilantro' },
  { label: 'Balsamic vinaigrette', value: 'balsamic_vinaigrette', desc: 'Balsamic vinaigrette' },
  { label: 'Strawberries, vinaigrette', value: 'strawberries_vinaigrette', desc: 'Strawberries, vinaigrette' },
  { label: 'Puff pastry, herbs', value: 'puff_pastry_herbs', desc: 'Puff pastry, herbs' },
  { label: 'Vinegar, herbs', value: 'vinegar_herbs', desc: 'Vinegar, herbs' },
  { label: 'Herbs, breadcrumbs', value: 'herbs_breadcrumbs', desc: 'Herbs, breadcrumbs' },
  { label: 'Lemon pepper seasoning', value: 'lemon_pepper_seasoning', desc: 'Lemon pepper seasoning' },
  { label: 'Shawarma seasoning', value: 'shawarma_seasoning', desc: 'Shawarma seasoning' },
  { label: 'Burrito seasoning', value: 'burrito_seasoning', desc: 'Burrito seasoning' },
  { label: 'Raspberries, vinaigrette', value: 'raspberries_vinaigrette', desc: 'Raspberries, vinaigrette' },
  { label: 'Rice, vegetables', value: 'rice_vegetables', desc: 'Rice, vegetables' },
  { label: 'Herbs', value: 'herbs', desc: 'Herbs' },
  { label: 'Biryani masala, spices', value: 'biryani_masala_spices', desc: 'Biryani masala, spices' },
  { label: 'Chole masala, spices', value: 'chole_masala_spices', desc: 'Chole masala, spices' },
  { label: 'Potato masala, spices', value: 'potato_masala_spices', desc: 'Potato masala, spices' },
  { label: 'Cauliflower, spices', value: 'cauliflower_spices', desc: 'Cauliflower, spices' },
  { label: 'Basmati rice, spices', value: 'basmati_rice_spices', desc: 'Basmati rice, spices' },
  { label: 'Pav bun, chutney', value: 'pav_bun_chutney', desc: 'Pav bun, chutney' },
  { label: 'Spiced water, chutney', value: 'spiced_water_chutney', desc: 'Spiced water, chutney' },
  { label: 'Curry spices', value: 'curry_spices', desc: 'Curry spices' },
  { label: 'Masala spices', value: 'masala_spices', desc: 'Masala spices' },
  { label: 'Mustard seeds, curry leaves', value: 'mustard_seeds_curry_leaves', desc: 'Mustard seeds, curry leaves' },
  { label: 'Pav bread, spices', value: 'pav_bread_spices', desc: 'Pav bread, spices' },
  { label: 'Meat/vegetables, spices', value: 'meat_vegetables_spices', desc: 'Meat/vegetables, spices' },
  { label: 'Potato masala, chutney', value: 'potato_masala_chutney', desc: 'Potato masala, chutney' },
  { label: 'Kulcha bread, spices', value: 'kulcha_bread_spices', desc: 'Kulcha bread, spices' },
  { label: 'Manchurian sauce', value: 'manchurian_sauce', desc: 'Manchurian sauce' },
  { label: 'Satay sauce, spices', value: 'satay_sauce_spices', desc: 'Satay sauce, spices' },
];

export const fatOilOptions: SelectProps['options'] = [
  { label: 'Butter', value: 'butter', desc: 'Butter' },
  { label: 'None', value: 'none', desc: 'None' },
  { label: 'Vegetable oil', value: 'vegetable_oil', desc: 'Vegetable oil' },
  { label: 'Olive oil', value: 'olive_oil', desc: 'Olive oil' },
  { label: 'Caesar dressing', value: 'caesar_dressing', desc: 'Caesar dressing' },
  { label: 'Yogurt (milk, cultures)', value: 'yogurt_milk_cultures', desc: 'Yogurt (milk, cultures)' },
  { label: 'Sour cream', value: 'sour_cream', desc: 'Sour cream' },
  { label: 'Bread crumbs, Parmesan cheese', value: 'bread_crumbs_parmesan_cheese', desc: 'Bread crumbs, Parmesan cheese' },
  { label: 'Milk', value: 'milk', desc: 'Milk' },
  { label: 'Cream cheese, sour cream', value: 'cream_cheese_sour_cream', desc: 'Cream cheese, sour cream' },
  { label: 'Heavy cream', value: 'heavy_cream', desc: 'Heavy cream' },
  { label: 'Yogurt', value: 'yogurt', desc: 'Yogurt' },
  { label: 'Ghee', value: 'ghee', desc: 'Ghee' },
  { label: 'Oil', value: 'oil', desc: 'Oil' },
  { label: 'Cream', value: 'cream', desc: 'Cream' },
  { label: 'Milk, Ghee', value: 'milk_ghee', desc: 'Milk, Ghee' },
  { label: 'Cheese', value: 'cheese', desc: 'Cheese' },
  { label: 'Sesame oil', value: 'sesame_oil', desc: 'Sesame oil' },
  { label: 'Coconut oil', value: 'coconut_oil', desc: 'Coconut oil' },
  { label: 'Soy sauce', value: 'soy_sauce', desc: 'Soy sauce' },
  { label: 'Milk powder', value: 'milk_powder', desc: 'Milk powder' },
  { label: 'Mustard', value: 'mustard', desc: 'Mustard' },
  { label: 'Water', value: 'water', desc: 'Water' },
  { label: 'Pancetta', value: 'pancetta', desc: 'Pancetta' },
  { label: 'Coconut milk', value: 'coconut_milk', desc: 'Coconut milk' },
  { label: 'Avocado', value: 'avocado', desc: 'Avocado' },
  { label: 'Pesto sauce', value: 'pesto_sauce', desc: 'Pesto sauce' },
  { label: 'Peanut butter', value: 'peanut_butter', desc: 'Peanut butter' },
  { label: 'Peanut oil', value: 'peanut_oil', desc: 'Peanut oil' },
  { label: 'Mayonnaise', value: 'mayonnaise', desc: 'Mayonnaise' },
  { label: 'Bacon', value: 'bacon', desc: 'Bacon' },
  { label: 'Whipped cream', value: 'whipped_cream', desc: 'Whipped cream' },
  { label: 'Enchilada sauce', value: 'enchilada_sauce', desc: 'Enchilada sauce' },
  { label: 'Chocolate', value: 'chocolate', desc: 'Chocolate' },
  { label: 'Mascarpone cheese', value: 'mascarpone_cheese', desc: 'Mascarpone cheese' },
  { label: 'Mascarpone cheese, coffee liqueur', value: 'mascarpone_cheese_coffee_liqueur', desc: 'Mascarpone cheese, coffee liqueur' },
];

export const sweetenerOptions: SelectProps['options'] = [
  { label: 'Sugar', value: 'sugar', desc: 'Sugar' },
  { label: 'None', value: 'none', desc: 'None' },
  { label: 'Honey', value: 'honey', desc: 'Honey' },
  { label: 'Brown sugar', value: 'brown_sugar', desc: 'Brown sugar' },
  { label: 'Mayonnaise', value: 'mayonnaise', desc: 'Mayonnaise' },
  { label: 'Rice vinegar', value: 'rice_vinegar', desc: 'Rice vinegar' },
  { label: 'Cocoa butter', value: 'cocoa_butter', desc: 'Cocoa butter' },
  { label: 'Caramel', value: 'caramel', desc: 'Caramel' },
  { label: 'Tamarind', value: 'tamarind', desc: 'Tamarind' },
  { label: 'Marshmallows', value: 'marshmallows', desc: 'Marshmallows' },
];

export const options: SelectProps['options'] = [
  { label: 'Almonds', value: 'almonds', desc: 'Almonds' },
  { label: 'Chicken broth', value: 'chicken_broth', desc: 'Chicken broth' },
  { label: 'Cheese', value: 'cheese', desc: 'Cheese' },
  { label: 'Buttermilk', value: 'buttermilk', desc: 'Buttermilk' },
  { label: 'Popcorn', value: 'popcorn', desc: 'Popcorn' },
  { label: 'Romaine lettuce', value: 'romaine_lettuce', desc: 'Romaine lettuce' },
  { label: 'Grilled chicken', value: 'grilled_chicken', desc: 'Grilled chicken' },
  { label: 'Strawberries', value: 'strawberries', desc: 'Strawberries' },
  { label: 'Potatoes', value: 'potatoes', desc: 'Potatoes' },
  { label: 'Yogurt (milk, cultures)', value: 'yogurt_milk_cultures', desc: 'Yogurt (milk, cultures)' },
  { label: 'Tomatoes', value: 'tomatoes', desc: 'Tomatoes' },
  { label: 'Mixed berries', value: 'mixed_berries', desc: 'Mixed berries' },
  { label: 'Chicken', value: 'chicken', desc: 'Chicken' },
  { label: 'Pesto sauce', value: 'pesto_sauce', desc: 'Pesto sauce' },
  { label: 'Beef', value: 'beef', desc: 'Beef' },
  { label: 'Bananas', value: 'bananas', desc: 'Bananas' },
  { label: 'Watermelon', value: 'watermelon', desc: 'Watermelon' },
  { label: 'Mango', value: 'mango', desc: 'Mango' },
  { label: 'Cucumbers', value: 'cucumbers', desc: 'Cucumbers' },
  { label: 'Butternut squash', value: 'butternut_squash', desc: 'Butternut squash' },
  { label: 'Pasta', value: 'pasta', desc: 'Pasta' },
  { label: 'Lamb', value: 'lamb', desc: 'Lamb' },
  { label: 'Mushrooms', value: 'mushrooms', desc: 'Mushrooms' },
  { label: 'Greek yogurt', value: 'greek_yogurt', desc: 'Greek yogurt' },
  { label: 'Eggplant', value: 'eggplant', desc: 'Eggplant' },
  { label: 'Pizza dough', value: 'pizza_dough', desc: 'Pizza dough' },
  { label: 'Spinach', value: 'spinach', desc: 'Spinach' },
  { label: 'Chocolate', value: 'chocolate', desc: 'Chocolate' },
  { label: 'Portobello mushrooms', value: 'portobello_mushrooms', desc: 'Portobello mushrooms' },
  { label: 'Pumpkin', value: 'pumpkin', desc: 'Pumpkin' },
  { label: 'Berries', value: 'berries', desc: 'Berries' },
  { label: 'Paneer', value: 'paneer', desc: 'Paneer' },
  { label: 'Lentils', value: 'lentils', desc: 'Lentils' },
  { label: 'Cottage cheese', value: 'cottage_cheese', desc: 'Cottage cheese' },
  { label: 'Milk solids', value: 'milk_solids', desc: 'Milk solids' },
  { label: 'Lentil dumplings', value: 'lentil_dumplings', desc: 'Lentil dumplings' },
  { label: 'Milk', value: 'milk', desc: 'Milk' },
  { label: 'Rice', value: 'rice', desc: 'Rice' },
  { label: 'Chicken breast', value: 'chicken_breast', desc: 'Chicken breast' },
  { label: 'Bacon', value: 'bacon', desc: 'Bacon' },
  { label: 'Sweet potatoes', value: 'sweet_potatoes', desc: 'Sweet potatoes' },
  { label: 'Brie cheese', value: 'brie_cheese', desc: 'Brie cheese' },
  { label: 'Onions', value: 'onions', desc: 'Onions' },
  { label: 'Lamb/Chicken', value: 'lamb_chicken', desc: 'Lamb/Chicken' },
  { label: 'Eggs', value: 'eggs', desc: 'Eggs' },
  { label: 'Fish fillets', value: 'fish_fillets', desc: 'Fish fillets' },
  { label: 'Salmon fillet', value: 'salmon_fillet', desc: 'Salmon fillet' },
  { label: 'Salmon', value: 'salmon', desc: 'Salmon' },
  { label: 'Fish', value: 'fish', desc: 'Fish' },
  { label: 'Cod', value: 'cod', desc: 'Cod' },
  { label: 'Tuna', value: 'tuna', desc: 'Tuna' },
  { label: 'Fish (salmon, tuna)', value: 'fish_salmon_tuna', desc: 'Fish (salmon, tuna)' },
  { label: 'Sushi rice', value: 'sushi_rice', desc: 'Sushi rice' },
  { label: 'Sugar', value: 'sugar', desc: 'Sugar' },
  { label: 'Apples', value: 'apples', desc: 'Apples' },
  { label: 'Oranges', value: 'oranges', desc: 'Oranges' },
  { label: 'Cucumber', value: 'cucumber', desc: 'Cucumber' },
  { label: 'Ground beef', value: 'ground_beef', desc: 'Ground beef' },
  { label: 'Pork ribs', value: 'pork_ribs', desc: 'Pork ribs' },
  { label: 'Quinoa', value: 'quinoa', desc: 'Quinoa' },
  { label: 'Mixed vegetables', value: 'mixed_vegetables', desc: 'Mixed vegetables' },
  { label: 'Lemon juice', value: 'lemon_juice', desc: 'Lemon juice' },
  { label: 'Vegetables', value: 'vegetables', desc: 'Vegetables' },
  { label: 'Avocado', value: 'avocado', desc: 'Avocado' },
  { label: 'Black beans', value: 'black_beans', desc: 'Black beans' },
  { label: 'Mixed fruits', value: 'mixed_fruits', desc: 'Mixed fruits' },
  { label: 'Sausage', value: 'sausage', desc: 'Sausage' },
  { label: 'Bell peppers', value: 'bell_peppers', desc: 'Bell peppers' },
  { label: 'Cabbage', value: 'cabbage', desc: 'Cabbage' },
  { label: 'Zucchini', value: 'zucchini', desc: 'Zucchini' },
  { label: 'Chicken wings', value: 'chicken_wings', desc: 'Chicken wings' },
  { label: 'Tofu', value: 'tofu', desc: 'Tofu' },
  { label: 'Brussels sprouts', value: 'brussels_sprouts', desc: 'Brussels sprouts' },
  { label: 'Carrots', value: 'carrots', desc: 'Carrots' },
  { label: 'Chickpeas', value: 'chickpeas', desc: 'Chickpeas' },
  { label: 'Potato', value: 'potato', desc: 'Potato' },
  { label: 'Semolina', value: 'semolina', desc: 'Semolina' },
  { label: 'Kidney beans', value: 'kidney_beans', desc: 'Kidney beans' },
  { label: 'Fermented batter', value: 'fermented_batter', desc: 'Fermented batter' },
  { label: 'Basmati rice', value: 'basmati_rice', desc: 'Basmati rice' },
  { label: 'Cauliflower', value: 'cauliflower', desc: 'Cauliflower' },
  { label: 'Mutton', value: 'mutton', desc: 'Mutton' },
  { label: 'Oats', value: 'oats', desc: 'Oats' },
  { label: 'Peanuts', value: 'peanuts', desc: 'Peanuts' },
  { label: 'Shrimp', value: 'shrimp', desc: 'Shrimp' },
  { label: 'Prawns', value: 'prawns', desc: 'Prawns' },
  { label: 'Lobster', value: 'lobster', desc: 'Lobster' },
  { label: 'Soybeans', value: 'soybeans', desc: 'Soybeans' },
  { label: 'Miso paste', value: 'miso_paste', desc: 'Miso paste' },
  { label: 'Wheat flour', value: 'wheat_flour', desc: 'Wheat flour' },
  { label: 'Flour', value: 'flour', desc: 'Flour' },
  { label: 'Blueberries', value: 'blueberries', desc: 'Blueberries' },
  { label: 'Arborio rice', value: 'arborio_rice', desc: 'Arborio rice' },
  { label: 'Pineapple', value: 'pineapple', desc: 'Pineapple' },
  { label: 'Bread', value: 'bread', desc: 'Bread' },
  { label: 'Lime juice', value: 'lime_juice', desc: 'Lime juice' },
  { label: 'Cream cheese', value: 'cream_cheese', desc: 'Cream cheese' },
  { label: 'Graham crackers', value: 'graham_crackers', desc: 'Graham crackers' },
  { label: 'Ladyfingers', value: 'ladyfingers', desc: 'Ladyfingers' },
  { label: 'Dough', value: 'dough', desc: 'Dough' },
  { label: 'Pecans', value: 'pecans', desc: 'Pecans' },
];
